export class Province {
    code: string;
    name: string;
}

export const PROVINCE_CODES = [
    { code: 'N/A', name: 'N/A' },
    { code: 'MET', name: 'Metro Manila' },
    { code: 'ABR', name: 'Abra' },
    { code: 'AGN', name: 'Agusan del Norte' },
    { code: 'AGS', name: 'Agusan del Sur' },
    { code: 'AKL', name: 'Aklan' },
    { code: 'ALB', name: 'Albay' },
    { code: 'ANT', name: 'Antique' },
    { code: 'APA', name: 'Apayao' },
    { code: 'AUR', name: 'Aurora' },
    { code: 'BAS', name: 'Basilan' },
    { code: 'BAN', name: 'Bataan' },
    { code: 'BTN', name: 'Batanes' },
    { code: 'BTG', name: 'Batangas' },
    { code: 'BEN', name: 'Benguet' },
    { code: 'BIL', name: 'Biliran' },
    { code: 'BOH', name: 'Bohol' },
    { code: 'BUK', name: 'Bukidnon' },
    { code: 'BUL', name: 'Bulacan' },
    { code: 'CAG', name: 'Cagayan' },
    { code: 'CAN', name: 'Camarines Norte' },
    { code: 'CAS', name: 'Camarines Sur' },
    { code: 'CAM', name: 'Camiguin' },
    { code: 'CAP', name: 'Capiz' },
    { code: 'CAT', name: 'Catanduanes' },
    { code: 'CAV', name: 'Cavite' },
    { code: 'CEB', name: 'Cebu' },
    { code: 'COM', name: 'Compostela Valley' },
    { code: 'COT', name: 'Cotabato' },
    { code: 'DAV', name: 'Davao del Norte' },
    { code: 'DAS', name: 'Davao del Sur' },
    { code: 'DVO', name: 'Davao Occidental' },
    { code: 'DAO', name: 'Davao Oriental' },
    { code: 'DIN', name: 'Dinagat Islands' },
    { code: 'EAS', name: 'Eastern Samar' },
    { code: 'GUI', name: 'Guimaras' },
    { code: 'IFU', name: 'Ifugao' },
    { code: 'ILN', name: 'Ilocos Norte' },
    { code: 'ILS', name: 'Ilocos Sur' },
    { code: 'ILI', name: 'Iloilo' },
    { code: 'ISA', name: 'Isabela' },
    { code: 'KAL', name: 'Kalinga' },
    { code: 'LUN', name: 'La Union' },
    { code: 'LAG', name: 'Laguna' },
    { code: 'LAN', name: 'Lanao del Norte' },
    { code: 'LAS', name: 'Lanao del Sur' },
    { code: 'LEY', name: 'Leyte' },
    { code: 'MAG', name: 'Maguindanao' },
    { code: 'MAD', name: 'Marinduque' },
    { code: 'MAS', name: 'Masbate' },
    { code: 'MDC', name: 'Mindoro Occidental' },
    { code: 'MDR', name: 'Mindoro Oriental' },
    { code: 'MSC', name: 'Misamis Occidental' },
    { code: 'MSR', name: 'Misamis Oriental' },
    { code: 'MOU', name: 'Mountain Province' },
    { code: 'NEC', name: 'Negros Occidental' },
    { code: 'NER', name: 'Negros Oriental' },
    { code: 'NSA', name: 'Northen Samar' },
    { code: 'NUE', name: 'Nueva Ecija' },
    { code: 'NUV', name: 'Nueva Viscaya' },
    { code: 'PLW', name: 'Palawan' },
    { code: 'PAM', name: 'Pampanga' },
    { code: 'PAN', name: 'Pangasinan' },
    { code: 'QUE', name: 'Quezon' },
    { code: 'QUI', name: 'Quirino' },
    { code: 'RIZ', name: 'Rizal' },
    { code: 'ROM', name: 'Romblon' },
    { code: 'WSA', name: 'Samar' },
    { code: 'SAR', name: 'Sarangani' },
    { code: 'SIG', name: 'Siquijor' },
    { code: 'SOR', name: 'Sorsogon' },
    { code: 'SCO', name: 'South Cotabato' },
    { code: 'SLE', name: 'Southern Leyte' },
    { code: 'SUK', name: 'Sultan Kudarat' },
    { code: 'SLU', name: 'Sulu' },
    { code: 'SUN', name: 'Surigao del Norte' },
    { code: 'SUR', name: 'Surigao del Sur' },
    { code: 'TAR', name: 'Tarlac' },
    { code: 'TAW', name: 'Tawi-Tawi' },
    { code: 'ZMB', name: 'Zambales' },
    { code: 'ZAN', name: 'Zamboanga del Norte' },
    { code: 'ZAS', name: 'Zamboanga del Sur' },
    { code: 'ZSI', name: 'Zamboanga Sibugay' }
];

export const US_STATES = [
    { code: 'AL', name: 'Alabama' },
    { code: 'AK', name: 'Alaska' },
    { code: 'AS', name: 'American Samoa' },
    { code: 'AZ', name: 'Arizona' },
    { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'California' },
    { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' },
    { code: 'DE', name: 'Delaware' },
    { code: 'DC', name: 'District of Columbia' },
    { code: 'FM', name: 'Federated States of Micronesia' },
    { code: 'FL', name: 'Florida' },
    { code: 'GA', name: 'Georgia' },
    { code: 'GU', name: 'Guam' },
    { code: 'HI', name: 'Hawaii' },
    { code: 'ID', name: 'Idaho' },
    { code: 'IL', name: 'Illinois' },
    { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' },
    { code: 'KS', name: 'Kansas' },
    { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiana' },
    { code: 'ME', name: 'Maine' },
    { code: 'MH', name: 'Marshall Islands' },
    { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' },
    { code: 'MI', name: 'Michigan' },
    { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' },
    { code: 'MO', name: 'Missouri' },
    { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' },
    { code: 'NV', name: 'Nevada' },
    { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' },
    { code: 'NM', name: 'New Mexico' },
    { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'North Carolina' },
    { code: 'ND', name: 'North Dakota' },
    { code: 'MP', name: 'Northern Mariana Islands' },
    { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' },
    { code: 'OR', name: 'Oregon' },
    { code: 'PW', name: 'Palau' },
    { code: 'PA', name: 'Pennsylvania' },
    { code: 'PR', name: 'Puerto Rico' },
    { code: 'RI', name: 'Rhode Island' },
    { code: 'SC', name: 'South Carolina' },
    { code: 'SD', name: 'South Dakota' },
    { code: 'TN', name: 'Tennessee' },
    { code: 'TX', name: 'Texas' },
    { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' },
    { code: 'VI', name: 'Virgin Islands' },
    { code: 'VA', name: 'Virginia' },
    { code: 'WA', name: 'Washington' },
    { code: 'WV', name: 'West Virginia' },
    { code: 'WI', name: 'Wisconsin' },
    { code: 'WY', name: 'Wyoming' },
    { code: 'AA', name: 'Armed Forces Americas' },
    { code: 'AE', name: 'Armed Forces Europe' },
    { code: 'AP', name: 'Armed Forces Pacific' }
];


export const JPN_PREFECTURE = [
    { code: 'JP-01', name: 'Hokkaidō' },
    { code: 'JP-02', name: 'Aomori' },
    { code: 'JP-03', name: 'Iwate' },
    { code: 'JP-04', name: 'Miyagi' },
    { code: 'JP-05', name: 'Akita' },
    { code: 'JP-06', name: 'Yamagata' },
    { code: 'JP-07', name: 'Fukushima' },
    { code: 'JP-08', name: 'Ibaraki' },
    { code: 'JP-09', name: 'Tochigi' },
    { code: 'JP-10', name: 'Gunma' },
    { code: 'JP-11', name: 'Saitama' },
    { code: 'JP-12', name: 'Chiba' },
    { code: 'JP-13', name: 'Tōkyō' },
    { code: 'JP-14', name: 'Kanagawa' },
    { code: 'JP-15', name: 'Niigata' },
    { code: 'JP-16', name: 'Toyama' },
    { code: 'JP-17', name: 'Ishikawa' },
    { code: 'JP-18', name: 'Fukui' },
    { code: 'JP-19', name: 'Yamanashi' },
    { code: 'JP-20', name: 'Nagano' },
    { code: 'JP-21', name: 'Gifu' },
    { code: 'JP-22', name: 'Shizuoka' },
    { code: 'JP-23', name: 'Aichi' },
    { code: 'JP-24', name: 'Mie' },
    { code: 'JP-25', name: 'Shiga' },
    { code: 'JP-26', name: 'Kyōto' },
    { code: 'JP-27', name: 'Ōsaka' },
    { code: 'JP-28', name: 'Hyōgo' },
    { code: 'JP-29', name: 'Nara' },
    { code: 'JP-30', name: 'Wakayama' },
    { code: 'JP-31', name: 'Tottori' },
    { code: 'JP-32', name: 'Shimane' },
    { code: 'JP-33', name: 'Okayama' },
    { code: 'JP-34', name: 'Hiroshima' },
    { code: 'JP-35', name: 'Yamaguchi' },
    { code: 'JP-36', name: 'Tokushima' },
    { code: 'JP-37', name: 'Kagawa' },
    { code: 'JP-38', name: 'Ehime' },
    { code: 'JP-39', name: 'Kōchi' },
    { code: 'JP-40', name: 'Fukuoka' },
    { code: 'JP-41', name: 'Saga' },
    { code: 'JP-42', name: 'Nagasaki' },
    { code: 'JP-43', name: 'Kumamoto' },
    { code: 'JP-44', name: 'Ōita' },
    { code: 'JP-45', name: 'Miyazaki' },
    { code: 'JP-46', name: 'Kagoshima' },
    { code: 'JP-47', name: 'Okinawa' }
];

export const CHINA_STATES = [
    { code: 'AH', name: 'Anhui' },
    { code: 'BJ', name: 'Beijing' },
    { code: 'CQ', name: 'Chongqing' },
    { code: 'FJ', name: 'Fujian' },
    { code: 'GS', name: 'Gansu' },
    { code: 'GD', name: 'Guangdong' },
    { code: 'GX', name: 'Guangxi' },
    { code: 'GZ', name: 'Guizhou' },
    { code: 'HI', name: 'Hainan' },
    { code: 'HE', name: 'Hebei' },
    { code: 'HL', name: 'Heilongjiang' },
    { code: 'HA', name: 'Henan' },
    { code: 'HB', name: 'Hubei' },
    { code: 'HN', name: 'Hunan' },
    { code: 'NM', name: 'Inner Mongolia' },
    { code: 'JS', name: 'Jiangsu' },
    { code: 'JX', name: 'Jiangxi' },
    { code: 'JL', name: 'Jilin' },
    { code: 'LN', name: 'Liaoning' },
    { code: 'NX', name: 'Ningxia' },
    { code: 'QH', name: 'Qinghai' },
    { code: 'SN', name: 'Shaanxi' },
    { code: 'SD', name: 'Shandong' },
    { code: 'SH', name: 'Shanghai' },
    { code: 'SX', name: 'Shanxi' },
    { code: 'SC', name: 'Sichuan' },
    { code: 'TJ', name: 'Tianjin' },
    { code: 'XJ', name: 'Xinjiang' },
    { code: 'YZ', name: 'Xizang' },
    { code: 'YN', name: 'Yunnan' },
    { code: 'ZJ', name: 'Zhejiang' }
];


export const CANADA_PROVINCE = [
    { code: 'AB', name: 'Alberta' },
    { code: 'BC', name: 'British Columbia' },
    { code: 'MB', name: 'Manitoba' },
    { code: 'NB', name: 'New Brunswick' },
    { code: 'NL', name: 'Newfoundland and Labrador' },
    { code: 'NT', name: 'Northwest Territories' },
    { code: 'NS', name: 'Nova Scotia' },
    { code: 'NU', name: 'Nunavut' },
    { code: 'ON', name: 'Ontario' },
    { code: 'PE', name: 'Prince Edward Island' },
    { code: 'QC', name: 'Quebec' },
    { code: 'SK', name: 'Saskatchewan' },
    { code: 'YT', name: 'Yukon' }
];
